### ISSUE TITLE
The generators don't seem to be working

### ISSUE THREAD

**Issue by lastobelus** [slime-lang/phoenix_slime#14]
I'm a complete elixir/phoenix newbie, but my wild guess at why is that `priv` needs to be added to the files section in the mix.exs package function.

**Comment by doomspork** [comment]
At first glance it looks like you're correct @lastobelus.  Feel free to open a PR with those changes.

**Comment by maxneuvians** [comment]
That one totally goes on me - apologies for missing that. Thank you for report it @lastobelus
