### ISSUE TITLE
Inline javascript isn't rendered correctly

### ISSUE THREAD

**Issue by taakazazzz** [slime-lang/phoenix_slime#24]
I have this:

```
javascript:
  var something = {
    var1: #{Application.get_env(:aaa, :bbb)},
    var2: true,
    var3: false,
    var4: {
      env: "prod"
    }
  };

  (somefunction() { .... /* some code */ })
```

The output code it produces contains html tags, including tags that don't exist in html, and other kinds of crazy stuff and it's not valid js code. 

This

```
javascript:
  alert('Slim supports embedded javascript!')
```

produces this

```
<javascript><alert 'Slim supports embedded javascript!'></alert></javascript>
```

**Comment by doomspork** [comment]
Hi @taakazazzz Slime does not currently support other embedded engines _but_ there is an open PR to add support: https://github.com/slime-lang/slime/pull/101

**Comment by tht** [comment]
Any chance you could move to slim-v0.15? It was released a few days ago and does include embedded engines (including javascript).

**Comment by tht** [comment]
#26 switches to new slime v0.15. I've tested it with two small web projects. The output looks the same and the embedded javascript-engine works well.

**Comment by doomspork** [comment]
@taakazazzz  / @tht I am preparing to release a new version with the latest Slime. 👍
