### ISSUE TITLE
Trouble with using gettext in slime

### ISSUE THREAD

**Issue by taktes** [slime-lang/phoenix_slime#30]
Hello!

I have a strange trouble with using `gettext` in slime templates. I tried to do something like this:

```
span title=gettext("Text")
```

and this works fine, but when I try to do the same but with whitespaces in gettext:

```
span title=gettext("Text with whitespaces")
```

I got an error:

```
missing terminator: " (for string starting at line 1)
```

**Comment by lessless** [comment]
bump

**Comment by doomspork** [comment]
Certainly sounds like a bug, do you have an example application someone can look at?  I'm not personally using Slime + Gettext at this time.

**Comment by taktes** [comment]
@doomspork Yep, please, look at this https://github.com/TakteS/slime_gettext

You just should clone it and try to compile and you'll get an error.

**Comment by doomspork** [comment]
Thanks @TakteS, I'll take a peek today

**Comment by taktes** [comment]
Now I found that this is not only gettext trouble. The error occurs when some text with white spaces is enclosed in parentheses:

```
# Ok
div title=("Text")

# Error will occurs
div title=("Some text")
```

**Comment by doomspork** [comment]
This is likely an issue with the underlying Slime library's parser.

**Comment by Rakoth** [comment]
fixed
