### ISSUE TITLE
Inline rendering

### ISSUE THREAD

**Issue by fbjork** [slime-lang/phoenix_slime#38]
I'm trying to assign a CSS class inline from a method call, but it doesn't work. 

Is that supported in Slime?

```
li[class="#{active_link(@conn, :about)}"]
```

**Comment by doomspork** [comment]
@fbjork this may be a bug with parsing the CSS.  We'll have to look into this.

**Comment by fbjork** [comment]
@doomspork got it. Thanks!

**Comment by Rakoth** [comment]
fixed
