### ISSUE TITLE
Please update hex package

### ISSUE THREAD

**Issue by smpallen99** [slime-lang/phoenix_slime#39]
Can you please push a new version to hex so we can use with phoenix 1.3. Thanks...

**Comment by doomspork** [comment]
@smpallen99 done 👍

**Comment by smpallen99** [comment]
Thanks!! BTW, I just started using slim. I was amazed that, given my understanding for haml, that I was immediately productive. Seems like you have a lot more robust parser than we do in Calliope. When I get some time, I'm going to see If I can use your parser design to overhaul Calliope. However, right now I'm thinking I may like slim over haml :)

**Comment by doomspork** [comment]
Thanks for the kind words @smpallen99!  Glad you were able to get up and running so quickly.  Huge thanks to @Rakoth who completely overhauled the parser to make it even better.
