### ISSUE TITLE
Unexpectedly significant newline

### ISSUE THREAD

**Issue by pikeas** [slime-lang/phoenix_slime#41]
p.alert.alert-danger role="alert"= get_flash(@conn, :error)
      main role="main"
        = render @view_module, @view_template, assigns

Vs

      p.alert.alert-danger role="alert"= get_flash(@conn, :error)

      main role="main"
        = render @view_module, @view_template, assigns

The second case renders `<p></p>` with a newline inside the block. With Phoenix's default CSS, this is non-empty, so the alert box is always shown even when there is no error.

Is there a way to prevent Slime from treating the newline as significant?

**Comment by lee-dohm** [comment]
Do you have `config :slime, :keep_lines, true` in your `config/config.exs` or one of the environment specific includes? (It is suggested in the [Debugging section of the slime README](https://github.com/slime-lang/slime#debugging).) It can cause the symptom you're describing, I believe.

**Comment by pikeas** [comment]
That did the trick, thanks!
