### ISSUE TITLE
Trouble parsing line with delimiter wrapper

### ISSUE THREAD

**Issue by pikeas** [slime-lang/phoenix_slime#42]
link rel="stylesheet", href="#{static_path(@conn, "/css/app.css")}"

vs

    link[rel="stylesheet", href="#{static_path(@conn, "/css/app.css")}"]

vs

    link(rel="stylesheet", href="#{static_path(@conn, "/css/app.css")}")

The first and second examples work, the third fails with: `** (TokenMissingError) lib/foo/web/templates/layout/app.html.slim:26: missing terminator: "`

**Comment by pikeas** [comment]
This appears to be fixed on the master branch of Slime. However, commas between attributes aren't supported. Please close if that's intentional behavior.

**Comment by Rakoth** [comment]
@pikeas Commas between attributes are not allowed in ruby-slim or slime format. Also you don't need an interpolation for href attribute in this example, just use the following syntax:
```slim
link rel="stylesheet" href=static_path(@conn, "/css/app.css")
```

**Comment by Rakoth** [comment]
@doomspork I think it can be closed
