### ISSUE TITLE
Support safe navigation of structs/maps? Nil protection

### ISSUE THREAD

**Issue by wulymammoth** [slime-lang/phoenix_slime#43]
Ignoring/breaking the Law of Demeter, having been exposed to `#try` and the safe-navigation operator `&.` in Ruby, I'm beginning to miss it in Elixir-land.

I posed a question in Elixir Forum, before realizing somebody had already asked the same question here: https://elixirforum.com/t/maybe-nil-protection-for-nested-structs/468

I'm wondering if you'd be okay supporting the solution suggested there: a `Maybe` module with the function and macro.

**Comment by jonmast** [comment]
@sudostack I'd say this is out of scope for this project, you could try opening an issue at https://github.com/elixir-lang/elixir/ or maybe https://github.com/phoenixframework/phoenix

**Comment by wulymammoth** [comment]
@jonmast I disagree. However, having spent a lot more time in templates since this post, it's been much better to use unit-tested view functions/helpers that operate in their respective contexts/domains.

I will say that early on, with the help of José, we actually implemented `struct_get_in/2` at my company that operates in the same manner as `Kernel.get_in/2`, but its utility has diminished after establishing better patterns.
