### ISSUE TITLE
New hex release?

### ISSUE THREAD

**Issue by fbjork** [slime-lang/phoenix_slime#46]
Any plans on pushing a new hex release with the latest changes?

**Comment by doomspork** [comment]
@fbjork it'll need to be a release candidate unfortunately, hex prohibits stable releases with release candidate dependencies (1.3-rc).

**Comment by fbjork** [comment]
@doomspork Ok, an rc sounds great!

**Comment by fbjork** [comment]
@doomspork Now that phoenix 1.3 is out, perhaps we can get a new version on Hex? :)

**Comment by doomspork** [comment]
I'd really like to resolve the issue's people are seeing in master, I'm assuming you don't get the same complication errors and generate mistakes?

**Comment by fbjork** [comment]
@doomspork it works for me when I try locally. Would be great to see a new version on hex that works with Phoenix 1.3 and depends on the newly released slime 1.1.0

**Comment by fbjork** [comment]
@doomspork could we get another release pushed to Hex?

**Comment by doomspork** [comment]
0.10.0 is out @fbjork 👍
