### ISSUE TITLE
UndefinedFunctionError when running mix phoenix.gen.layout.slime

### ISSUE THREAD

**Issue by cdeyoung** [slime-lang/phoenix_slime#48]
Hello,

I'm seeing an UndefinedFunctionError when running 

`mix phoenix.gen.layout.slime`

in an umbrella app in Phoenix 1.3 RC3.  I'm using PhoenixSlime 0.9.0.  Here is the output:

`** (UndefinedFunctionError) function Mix.Phoenix.copy_from/5 is undefined or private. Did you mean one of:

      * copy_from/4

    Mix.Phoenix.copy_from([".", :phoenix_slime], "priv/templates/phoenix.gen.layout.slime", "", [application_module: "ApplicationName"], [{:eex, "app.html.eex", "web/templates/layout/app.html.slim"}])
    lib/mix/tasks/phoenix.gen.layout.slime.ex:16: Mix.Tasks.Phoenix.Gen.Layout.Slime.run/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
    (elixir) lib/code.ex:376: Code.require_file/2`

This is happening in a new Phoenix umbrella app, which was generated via the following command:

`mix phx.new portal --umbrella`

The only thing I've changed from the default configuration is adding PhoenixSlime to the project.  Please let me know if you need any further information.

**Comment by doomspork** [comment]
@cdeyoung now that 1.3 is out we need to update this package!  Would you like to help?  It would be greatly appreciated 😀

**Comment by doomspork** [comment]
Closed in #51
