### ISSUE TITLE
Support a sigil for safe HTML

### ISSUE THREAD

**Issue by the-mikedavis** [slime-lang/phoenix_slime#61]
EEx has [a sigil for doing safe HTML in your Elixir code](https://hexdocs.pm/phoenix_html/Phoenix.HTML.html#sigil_E/2). At first look it doesn't seem to be too interesting, but with the new [LiveView](https://shift.infinite.red/phoenixs-liveview-client-side-elixir-at-last-2280716ae791) coming up, it looks pretty useful.

I hate writing Eex, love writing Slime. It'd be cool to be able to write slime in the live view, and it seems to me like a sigil for this is the first step in the right direction.

(Feature request)

**Comment by doomspork** [comment]
@the-mikedavis would you be open to taking a first stab at this?  We'd welcome a PR 😁

**Comment by doomspork** [comment]
That's a good question @the-mikedavis 🤔.  @Rakoth do you have any preference?  I'm leaning towards `L`.
