### ISSUE TITLE
Add Routes as module for path functions for Phoenix >= 1.4

### ISSUE THREAD

**Issue by sveredyuk** [slime-lang/phoenix_slime#62]
I could try to add this feature for upcoming Phoenix 1.4 release.

```ex
# Phoenix 1.3
static_path

# Phoenix 1.4
Routes.static_path
```

**Comment by sveredyuk** [comment]
@doomspork Nice. Always wanna take participation in Hacktoberfest and this look like a good opportunity.

How I should implement this?

- Backward compatibility for Phoenix 1.3 ?
- Mix generators with `if` condition or split in 2 different templates for generators ?
- Any other suggestions...

**Comment by doomspork** [comment]
That's a good question @sveredyuk 🤔  I believe @scarfacedeb's changes in #64 are not backwards compatible so these changes need not be.  I'm kind of the mind that we encourage people to upgrade to the latest Phoenix along with the latest Slime.  If they can't, they can continue to use an older version of `phoenix_slime`.

Any thoughts @Rakoth / @scarfacedeb?

**Comment by sveredyuk** [comment]
I also think that backward compatibility it's legacy. Anyway people that use generators, use it for newest stable phoenix version. Task would be much simple without mind about Phoenix 1.3 support.

**Comment by scarfacedeb** [comment]
I think that generators are mostly used by newer projects, therefore it should be ok to drop phoenix 1.3 support for the generators.

**Comment by sveredyuk** [comment]
On my way

**Comment by the-mikedavis** [comment]
I've been using phoenix from the master branch with slime for a little while and it seems to me like `Routes.*` works without any modification. I have a project with a whole bunch of

```slim
li = link("Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete")
...
link rel="stylesheet" href="#{Routes.static_path(@conn, "/css/app.css")}"
```

And all those links and resources seem to be coming in fine. I think `Routes` is just an alias dropped in by the view module [from `Phoenix.Router.Helpers`](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/router/helpers.ex#L147).

**Comment by sveredyuk** [comment]
@the-mikedavis Yes, if you added `Routes` module to your existing path macros. We discussing here generators for slime. Now templates are not support `Routes` module
