### ISSUE TITLE
New Mix version

### ISSUE THREAD

**Issue by PJUllrich** [slime-lang/phoenix_slime#74]
Hi there,

I'd like to humbly ask whether you could upload a new version of this library to `mix` please? Version `0.12.0` is from `Dec 2018` and does not include LiveViewEngine. A new version including all the changes since Dec 2018 would be nice to have (for a CI without git dependencies for example)

Much appreciated!

**Comment by doomspork** [comment]
Done! Sorry about that @PJUllrich
