### ISSUE TITLE
Inconsistency in generator between new and edit templates

### ISSUE THREAD

**Issue by liamwhite** [slime-lang/phoenix_slime#76]
edit:
https://github.com/slime-lang/phoenix_slime/blob/d8af8bc08ddb33962cbec63f744393bd0805c6a4/priv/templates/phx.gen.html/edit.html.eex#L3
**new**:
https://github.com/slime-lang/phoenix_slime/blob/d8af8bc08ddb33962cbec63f744393bd0805c6a4/priv/templates/phx.gen.html/new.html.eex#L3

The `new` template is incorrect and should use `route_helper` instead of `singular` (this is relevant when using the --web option).

**Comment by doomspork** [comment]
@liamwhite thank you for pointing this out! Would you be willing to open a PR to make this correction?

**Comment by liamwhite** [comment]
resolved by #77
