### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by lpil** [slime-lang/phoenix_slime#9]
PhoenixSlime ?

**Comment by doomspork** [comment]
I messaged you about this on IRC yesterday to get your thoughts.  I'm all for updating the name my only reservation is whether it would make it more difficult for people looking for Slim on Phoenix to find it.

Thoughts?

**Comment by lpil** [comment]
I don't think it makes sense if this is no longer slim. We'll just have to work on our marketing so that this project is easy to find. We can refer to slim and jade in the package documentation.

**Comment by doomspork** [comment]
Sounds good.  I can update the repos and packages later today.
